serenity.project.name=Set de Pruebas Automaticas
serenity.report.encoding=UTF-8
serenity.report.accessibility=true
report.customfields.Environment = ${environment}
report.customfields.order = Environment