## General Serenity Config
serenity {
    console.colors=true
    project.name=Automated Tests
    take.screenshots=FOR_FAILURES
    appium.timeout=60
    restart.browser.for.each=SCENARIO
}

feature.file.language=en

## Default Environment
environment=api-qa
darkMode=false

## Test Data
test.data.resource.relative.file.path="data/usertestdata.json"

##Threshold to consider an execution as successful
test.api.success.threshold=0.9
test.ui.success.threshold=0.8

## API General Parameters
api {
    schemas.folder="data/restapi/schemas/"
    login.after.wait.ms=500
}

environments {
    api-dev {
        data.env=dev
    }
    api-qa {
        data.env=qa
    }
}